add_newline = false
format = "$all"

# Change prompt logo
[character]
#success_symbol = " [ğŸ—¡ï¸](bold green)"
#error_symbol = " [â˜ ï¸](bold red)"
#success_symbol = "[âœ](bold green) "
#error_symbol = "[âœ](bold red) "
#success_symbol = "[â‡](bold green)"
#error_symbol = "[â‡](bold red)"
#success_symbol = "[Â»](bold green)"
#error_symbol = "[Â»](bold red)"
#success_symbol = "[â¸](bold green)"
#error_symbol = "[â¸](bold red)"
success_symbol = "[â«](bold green)"
error_symbol = "[â«](bold red)"

[cmd_duration]
format = "took [$duration]($style)"
style = "bold-yellow"

[kubernetes]
format = '[$namespace in $context]($style) '
style = "#3dcafc"
symbol = ""
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:us-west-2:389177558658:cluster/pac-devops-virtualrack-cloud-eks-cluster-dev" = "eks-cluster-dev"

[golang]
format = "via [go $version]($style) "
symbol = "ğŸ ğŸ’¨"
style = "blue"

[lua]
symbol = "ğŸŒ™" 
format = "[$symbol $version]($style) "
style = "bold blue"

[rust]
format = "via [$symbol $version]($style) "
symbol = "ğŸ¦€"
style = "bold red"

[helm]
format = "via [$symbol $version]($style) "
symbol = "helm"
style = "bold blue"

[git_branch]
symbol = "ï˜"
format = "[$symbol $branch]($style) "
style = "bright-purple"

[git_metrics]
disabled = true

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
conflicted = "ğŸ³"
untracked = ""
up_to_date = "âœ“"
stashed = ""
modified = ""
staged = '[++\($count\)](green)'
renamed = ""
deleted = ""

[package]
format = "[$symbol $version]($style) " 
symbol = "ğŸ“¦"
style = "bold 208"
disabled = true

[docker_context]
disabled = true
